imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: config/fos_elastica.yml }
    - { resource: config/liip_imagine.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    name: "PrintABrick"
    # rebrickable csv files root URL (http://rebrickable.com/media/downloads/ or local dir containing csv files)
    app.rebrickable_downloads_url: 'http://rebrickable.com/media/downloads/'
    app.ld_library_download_url: 'http://www.ldraw.org/library/updates/complete.zip'

    app.media_root: "%kernel.root_dir%/../var/media/"

framework:
    #esi:             ~
    translator:
        fallbacks: ["%locale%"]
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    globals:
        name: "%name%"
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes: ['form/semantic-ui.html.twig', 'form/search.html.twig']

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        options:
            1001: true
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

monolog:
    channels: ['loader']
    use_microseconds: false
    handlers:
        elasticsearch:
            type: stream
            level: error
        loader:
            type: rotating_file
            path: "%kernel.logs_dir%/loader.log"
            level: debug
            channels: 'loader'
            max_files: 5
#            stop_buffering:       true
#            buffer_size:          0

knp_menu:
    twig:
        template: menu/knp_menu.html.twig
    templating: false
    default_renderer: twig

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: dir       # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: :pagination:knp_pagination.html.twig
        sortable: :pagination:sortable_link.html.twig

oneup_flysystem:
    adapters:
        media:
            local:
                directory: "%app.media_root%"
    filesystems:
        media:
            adapter: media