imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   printabrick_testdb
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        options:
            1001: true

oneup_flysystem:
    adapters:
        media:
            local:
                directory: "%kernel.cache_dir%/filesystem"
    filesystems:
        media:
            adapter: media